INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('7889955', 'Alberto', 'Solano Pariona', 'alberto.pariona@empresa.com', '998645632', 'V', 'A', TO_DATE('20/02/1970', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('45781233', 'Alicia', 'Garcia Campos', NULL, NULL, 'C', 'A', TO_DATE('10/03/1980', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('5487922', 'Juana', 'Avila Chumpitaz', 'juana.avila@gmail.com', '923568741', 'C', 'A', TO_DATE('06/06/1986', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('22116633', 'Ana', 'Enriquez Flores', 'ana.enriquez@empresa.com', NULL, 'V', 'A', TO_DATE('10/02/1970', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('88741589', 'Claudia', 'Perales Ortiz', 'claudia.perales@yahoo.com', '997845263', 'C', 'A', TO_DATE('25/07/1981', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('45122587', 'Mario', 'Barrios Martinez', 'mario.barrios@outlook.com', '98652587', 'C', 'A', TO_DATE('10/10/1987', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('15258564', 'Brunela', 'Tarazona Guerra', 'brunela.tarazona@gmail.com', '995236741', 'C', 'A', TO_DATE('06/06/1990', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('4742536', 'Alejandro', 'Jimenez Huapaya', NULL, '941525365', 'C', 'A', TO_DATE('01/06/1989', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('15352585', 'Claudia', 'Marquez Litano', 'claudia.marquez@gmail.com', '985014723', 'C', 'A', TO_DATE('01/10/1991', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('45772587', 'Mario', 'Rodriguez Mayo', 'mario.rodriguez@outlook.com', '912662587', 'C', 'A', TO_DATE('10/11/1987', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('87952514', 'Luisa', 'Guerra Ibarra', 'luisa.guerra@yahoo.com', '974422136', 'C', 'A', TO_DATE('21/12/1988', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('74142585', 'Pedro Alberto', 'Candela Valenzuela', 'pedro.candela@gmail.com', '94149525', 'C', 'A', TO_DATE('30/06/1995', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('53298147', 'Angel Manuel', 'Rojas Avila', 'angel.rojas@outlook.com', NULL, 'C', 'A', TO_DATE('02/03/1975', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('11453265', 'Hilario Fabiano', 'Avila Huapaya', NULL, '985514326', 'C', 'A', TO_DATE('02/05/2000', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('75747218', 'Octavio Adan', 'Marquez Osorio', 'octavio.marquez@yahoo.es', '966223141', 'C', 'A', TO_DATE('22/09/2000', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('55586932', 'Manolo Enrique', 'Vasquez Saravia', 'manolo.vasquez@outlook.es', '966223141', 'C', 'A', TO_DATE('22/09/2000', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('41552567', 'Genoveva Pilar', 'Ortiz Quispe', 'genoveva.ortiz@outlook.es', '92564137', 'C', 'A', TO_DATE('12/04/2003', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('4985471', 'Oscar César', 'Quiroz Zavala', NULL, '988223145', 'C', 'A', TO_DATE('06/09/2004', 'DD/MM/YYYY'));
INSERT INTO persona (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('44992217', 'Veronica', 'Romero Vargas', 'veronica.romero@yahoo.com', NULL, 'V', 'A', TO_DATE('25/08/2002', 'DD/MM/YYYY'));

COMMIT;

/* PASO 5 */
INSERT INTO CATEGORIA (IDCAT, NOMCAT) VALUES (10, 'Abarrotes');
INSERT INTO CATEGORIA (IDCAT, NOMCAT) VALUES (20, 'Carnes y Pollo');
INSERT INTO CATEGORIA (IDCAT, NOMCAT) VALUES (30, 'Higiene y Limpieza');
INSERT INTO CATEGORIA (IDCAT, NOMCAT) VALUES (40, 'Bebidas y licores');
INSERT INTO CATEGORIA (IDCAT, NOMCAT) VALUES (50, 'Dulces y snacks');
INSERT INTO CATEGORIA (IDCAT, NOMCAT) VALUES (60, 'Electrodomésticos');






/*PASO 6*/

/*PASO 6*/
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P01', 'Arroz', 4.65, 50, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P02', 'Azucar', 3.45, 60, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P03', 'Pollo fresco', 8.7, 20, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P04', 'Lomo fino', 10.5, 40, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P05', 'Detergente Opal', 8.75, 60, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P06', 'Suavizante Ariel', 7.85, 30, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P07', 'Six pack cerveza en lata', 19.85, 150, 40, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P08', 'Pack Johnnie Walker Black', 119.75, 150, 40, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P09', 'Ron Barceló gran añejo', 68.95, 150, 40, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P10', 'Filete de pechuga', 25.55, 50, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P11', 'Deditos de pechuga de pollo', 12.75, 120, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P12', 'Hamburguesa premium parrillera', 28.75, 150, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P13', 'Nugget de pollo', 10.9, 100, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P14', 'Tiras de pechuga de pollo', 13.5, 250, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P15', 'Galletas Oreo', 6.88, 50, 50, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P16', 'Galleta Choco Donuts', 4.9, 90, 50, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P17', 'Huevo de pascua', 35.9, 70, 50, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P18', 'Bombones de chocolate', 3.4, 100, 50, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P19', 'Detergente en polvo opal 6KG.', 50.25, 250, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P20', 'Detergente Marsella Aromaterapia 4KG.', 46.1, 150, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P21', 'Detergente líquido aroma bebé 5L', 83.85, 200, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P22', 'Jabón para lavar Caricia 200G.', 7.75, 90, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P23', 'Lejía tradicional 18KG', 24.75, 200, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P24', 'Jabón para lavar - Bolivar', 6.8, 100, 30, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P25', 'Pack de menestras de lenteja', 14.5, 120, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P26', 'Mayonesa Alacena 850GR.', 16.9, 90, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P27', 'Aceite de oliva extra virgen', 32.5, 145, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P28', 'Fideos tallarín 500G', 3.9, 45, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P29', 'Crema de avellanas con cacao', 7.8, 200, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P30', 'Harina de trigo sin preparar', 8.1, 100, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P31', 'Maicena Universal 180GR', 2.9, 85, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P32', 'Harina de maíz blanco', 10.5, 85, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P33', 'Leche condensada nestlé', 6.2, 135, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P34', 'Duraznos en almíbar', 13.6, 180, 10, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P35', 'Chicharrón de cerdo', 29.5, 165, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P36', 'Apanado de pollo', 37.95, 90, 20, 'A');
INSERT INTO PRODUCTO (CODPROD, NOMPRO, PREPRO, STOCKPRO, IDCAT, ESTPRO) VALUES ('P37', 'Sopa de carne', 9.6, 170, 20, 'A');

COMMIT;





/*Paso 7*/
INSERT INTO VENTA (IDVEN, FECVEN, IDVEND, IDCLI, TIPPAGVEN, ESTVEN) VALUES (1, TO_DATE('25/04/2023', 'DD/MM/YYYY'), 200, 202, 'E', 'A');
INSERT INTO VENTA (IDVEN, FECVEN, IDVEND, IDCLI, TIPPAGVEN, ESTVEN) VALUES (2, TO_DATE('25/04/2023', 'DD/MM/YYYY'), 200, 204, 'T', 'A');
INSERT INTO VENTA (IDVEN, FECVEN, IDVEND, IDCLI, TIPPAGVEN, ESTVEN) VALUES (3, TO_DATE('25/04/2023', 'DD/MM/YYYY'), 203, 205, 'T', 'A');
INSERT INTO VENTA (IDVEN, FECVEN, IDVEND, IDCLI, TIPPAGVEN, ESTVEN) VALUES (4, TO_DATE('25/04/2023', 'DD/MM/YYYY'), 203, 206, 'E', 'A');



/*PASO 8*/
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (300, 1, 'P01', 2);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (301, 1, 'P04', 4);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (302, 2, 'P06', 12);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (303, 2, 'P08', 6);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (304, 2, 'P11', 16);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (305, 3, 'P15', 8);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (306, 4, 'P09', 5);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (307, 4, 'P14', 13);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (308, 4, 'P20', 10);
INSERT INTO VENTA_DETALLE (IDVENDET, IDVEN, CODPROD, CANVENDET) VALUES (309, 4, 'P21', 13);



/*PASO 9 ACTUALIZAR celular de  Mario Rodríguez Martínez*/
UPDATE PERSONA SET CELPER = '922881101' WHERE DNIPER = '45772587';


/*PASO 10 ACTUALIZAR celular de  número de celular de Ángel Manuel Rojas Ávila*/
UPDATE PERSONA SET CELPER = '977226604' WHERE DNIPER = '53298147';


/* PASO 11 Eliminar lógicamente a los clientes con DNI específicos*/
UPDATE PERSONA SET ESTPER = 'I' WHERE DNIPER IN ('11453265', '15487922', '49985471');


/*Paso 12  Eliminar físicamente a los clientes con DNI específicos*/
DELETE FROM PERSONA WHERE DNIPER IN ('87952514', '555869321', '74142585');


/*Paso 13 Actualizar el correo de Oscar César Quiroz Zavala*/
UPDATE PERSONA SET EMAPER = 'oscar.quiroz@yahoo.es', ESTPER = 'A' WHERE DNIPER = '49985471';


/*paso 14 Agregar los nuevos registros de clientes y vendedores*/
INSERT INTO PERSONA (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('88225463', 'Gustavo Tadeo', 'Quispe Solorzano', 'gustavo.quispe@gmail.com', NULL, 'V', 'A', TO_DATE('13/10/2021', 'DD/MM/YYYY'));
INSERT INTO PERSONA (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('15753595', 'Daniela', 'Solis Vargas', 'daniela.solis@outlook.com', NULL, 'C', 'A', TO_DATE('09/11/1993', 'DD/MM/YYYY'));
INSERT INTO PERSONA (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('76314898', 'Milton Gregorio', 'Vasquez Saravia', 'milton.gregorio@yahoo.es', '974815233', 'C', 'A', TO_DATE('22/06/2004', 'DD/MM/YYYY'));
INSERT INTO PERSONA (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('84725001', 'Verónica', 'Ancajima Araujo', 'veronica.ancajima@outlook.com', NULL, 'C', 'A', TO_DATE('07/11/1900', 'DD/MM/YYYY'));
INSERT INTO PERSONA (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('11226514', 'Felicita', 'Marroquin Candela', 'felicita.marroquin@outlook.com', '966001472', 'V', 'A', TO_DATE('06/06/2006', 'DD/MM/YYYY'));
INSERT INTO PERSONA (DNIPER, NOMPER, APEPER, EMAPER, CELPER, TIPPER, ESTPER, FECNACPER) VALUES ('51436952', 'Luhana', 'Ortiz Rodriguez', 'luhana.ortiz@outlook.com', '964040501', 'C', 'A', TO_DATE('25/11/1980', 'DD/MM/YYYY'));


/*paso 15 Actualizar el precio de la Maicena Universal*/
UPDATE PRODUCTO SET PREPRO = 3.5 WHERE CODPROD = 'P31';


/*Paso 16 Actualizar el nombre de un producto*/
UPDATE PRODUCTO SET NOMPRO = 'Detergente Opal 1/2kg.' WHERE CODPROD = 'P05';


/* paso 17 Eliminar productos específicos*/
DELETE FROM PRODUCTO WHERE NOMPRO = 'Apanado de pollo' OR NOMPRO = 'Sopa de carne';


/*paso 18 Eliminar productos por su código*/
DELETE FROM PRODUCTO WHERE CODPROD IN ('P13', 'P16', 'P19');

/* paso 19 Eliminar productos según su precio*/
SELECT CODPROD FROM PRODUCTO WHERE PREPRO <= 10;

/*paso 20 Eliminar una categoría*/
DELETE FROM CATEGORIA WHERE NOMCAT = 'Electrodomésticos';